apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

grafana:
  environment:
    - GF_DATABASE_TYPE=mysql
    - GF_DATABASE_HOST=host.docker.internal:3306
    - GF_DATABASE_NAME=grafana
    - GF_DATABASE_USER=root
    - GF_DATABASE_PASSWORD=123456
